# Generated by Django 4.0.4 on 2022-06-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(default='https://www.cisin.com/coffee-break/components/com_easyblog/themes/wireframe/images/placeholder-image.png', max_length=10000),
        ),
    ]
