# Generated by Django 4.0.4 on 2022-06-16 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.buyer'),
            preserve_default=False,
        ),
    ]
